// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ficjjxnktmiudubyxmgd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZpY2pqeG5rdG1pdWR1Ynl4bWdkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0MjUxMTgsImV4cCI6MjA2MTAwMTExOH0.fbg_eJkFQQ-STBtA2lCjLLlxgl8xfEvoD9kxPTYzpHA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);